# Generated by Django 3.2 on 2022-05-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinformation',
            name='location',
            field=models.CharField(max_length=150, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='productreservation',
            name='pickup_date',
            field=models.DateField(verbose_name='Pickup Date'),
        ),
    ]
