# Generated by Django 3.2 on 2022-05-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220525_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='event_date',
            field=models.DateField(unique=True, verbose_name='Event Date'),
        ),
    ]
