# Generated by Django 3.2 on 2022-05-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220525_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_notes',
            field=models.TextField(blank=True, verbose_name='User Notes'),
        ),
    ]
