# Generated by Django 3.2 on 2022-05-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_user_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_notes',
        ),
    ]
