# Generated by Django 3.2 on 2022-05-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_customer_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_remarks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customernotes', verbose_name='Customer Notes'),
        ),
    ]
