# Generated by Django 3.2 on 2022-05-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220528_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='total_items_sold',
            new_name='total_orders',
        ),
    ]
