# Generated by Django 3.2 on 2022-05-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_total_items_sold_sales_total_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='delivery_fees',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total_income',
        ),
    ]
