# Generated by Django 3.2 on 2022-05-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220529_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='delivery_fees',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total_income',
        ),
    ]
