# Generated by Django 3.2 on 2022-05-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220529_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_remarks',
        ),
    ]
