# Generated by Django 3.2 on 2022-05-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20220529_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_feee',
        ),
    ]
