# Generated by Django 3.2 on 2022-05-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_order_delivery_feee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=1, verbose_name='Delivery Fee'),
            preserve_default=False,
        ),
    ]
