# Generated by Django 3.2 on 2022-05-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_delivery_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
    ]
