# Generated by Django 3.2 on 2022-05-29 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_deliveryfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfees',
            name='delivery_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.deliveryinformation', verbose_name='Barangay'),
            preserve_default=False,
        ),
    ]
