# Generated by Django 3.2 on 2022-05-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_deliveryfees_delivery_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryfees',
            options={'verbose_name_plural': 'Ang Pogi ko'},
        ),
        migrations.AddField(
            model_name='sales',
            name='total_products',
            field=models.PositiveIntegerField(default=1, verbose_name='Total Products Listed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryfees',
            name='delivery_fee',
            field=models.PositiveIntegerField(verbose_name='Fee'),
        ),
    ]
