# Generated by Django 3.2 on 2022-05-30 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20220529_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Report Date'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeliveryFees',
        ),
    ]
