# Generated by Django 3.2 on 2022-05-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20220530_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(default=1, verbose_name='Customer Notes'),
            preserve_default=False,
        ),
    ]
