# Generated by Django 3.2 on 2022-05-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_order_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(verbose_name='Customer Notes')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
    ]
