# Generated by Django 3.2 on 2022-05-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20220530_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.AddField(
            model_name='deliveryinformation',
            name='notes',
            field=models.TextField(default=1, verbose_name='Customer Notes'),
            preserve_default=False,
        ),
    ]
